### ISSUE TITLE
Updating for Ruby 2.7

### ISSUE THREAD

**Issue by jonallured** [atwam/money-historical-bank#10]
Hey there, I forked this project over here:

https://github.com/jonallured/money-historical-bank

And then did a series of PRs to get the project in a bit better shape:

* https://github.com/jonallured/money-historical-bank/pull/3
* https://github.com/jonallured/money-historical-bank/pull/4

I also added TravisCI setup and the project is building against all supported Ruby versions:

* 2.5
* 2.6
* 2.7

I did this because we use this project at work and a BigDecimal deprecation warning turned into a failure with Ruby 2.7. So yeah, I spent some time dusting things off and would love to get this upstream - lmk if you want to get this done and we could cut a release too! 🙌

**Comment by atwam** [comment]
Heya, I just looked at your changes, this all looks good!.
Do you mind sending a PR so I can merge this?
Cheers
