### ISSUE TITLE
How do you configure app_id?

### ISSUE THREAD

**Issue by dgilperez** [atwam/money-historical-bank#7]
It seems to be needed for the web service to work, but I can't find how to configure that. Setting `ENV['OPENEXCHANGERATES_APP_ID']` does not seem to work. 

Thanks!

**Comment by Techbrunch** [comment]
This should work, there is even a test for it: https://github.com/atwam/money-historical-bank/search?utf8=%E2%9C%93&q=OPENEXCHANGERATES_APP_ID&type=

This issue could be closed.

**Comment by atwam** [comment]
Thanks @Techbrunch for pointing out the solution. Closing.
